export const demoDepartments = [
  { id: 'demo-dept-nursing', name: 'Nursing', headName: 'Priyanka N S', status: 'Active' },
  { id: 'demo-dept-physiotherapy', name: 'Physiotherapy', headName: 'Priyanka N S', status: 'Active' },
  { id: 'demo-dept-allied-health', name: 'Allied Health Sciences', headName: 'Tejas M', status: 'Active' },
];

export const demoStaffMembers = [
  {
    id: 'demo-staff-deepashree-cl',
    employeeId: 'FAC-1001',
    name: 'Dr. Deepashree C L',
    staffType: 'Faculty',
    department: 'Allied Health Sciences',
    designation: 'Professor',
    phone: '',
    email: 'deeparajesh1301@gmail.com',
    qualification: 'PhD Microbiology, M.Sc Microbiology, B.Sc',
    institution: 'Heritage City Institute of Allied Health Sciences',
    city: 'Mysuru',
    dateOfBirth: '13 Aug 1986',
    specialization: 'Microbiology',
    joiningDate: '11 Dec 2023',
    appointmentType: 'Full-time',
    address: 'Mysuru, Karnataka',
    previousExperience: 'Teaching and academic experience certificates included from nursing and allied health institutions.',
    publications: 'Not recorded',
    researchProjects: 'Not recorded',
    qualificationDetails: [
      'PhD in Microbiology, University of Mysore',
      'M.Sc Microbiology, University of Mysore',
      'B.Sc, University of Mysore',
      'KSET Life Sciences qualified',
    ],
    documentFileName: 'Dr Deepashree C L (ALL Doc Merged).pdf',
    documentStatus: 'PDF available for upload',
    status: 'Active',
    createdAtText: '23 Jun 2026',
  },
  {
    id: 'demo-staff-harish-b',
    employeeId: 'FAC-1002',
    name: 'Harish B',
    staffType: 'Faculty',
    department: 'Nursing',
    designation: 'Principal',
    phone: '+91 78292 18454',
    email: 'harishb85@gmail.com',
    qualification: 'M.Sc Nursing, B.Sc Nursing',
    institution: 'Maurya College of Nursing',
    city: 'Mysore',
    dateOfBirth: '25 Jan 1985',
    specialization: 'Nursing',
    joiningDate: '10 Jan 2025',
    appointmentType: 'Principal',
    address: 'No. 32, 2nd Cross, Janathanagar, T.K. Layout, Mysore - 09',
    previousExperience: 'Nursing faculty experience recorded in the declaration form.',
    publications: 'International: 2; National: 1',
    researchProjects: 'Not recorded',
    qualificationDetails: [
      'M.Sc Nursing, GCON/RGUHS, 2011',
      'B.Sc Nursing, HMCON/RGUHS, 2007',
    ],
    documentFileName: 'HARISH B.pdf',
    documentStatus: 'PDF available for upload',
    status: 'Active',
    createdAtText: '23 Jun 2026',
  },
  {
    id: 'demo-staff-priyanka-ns',
    employeeId: 'FAC-1003',
    name: 'Priyanka N S',
    staffType: 'Faculty',
    department: 'Physiotherapy',
    designation: 'Principal',
    phone: '+91 99453 12644',
    email: 'priyanka.n.s.dug@gmail.com',
    qualification: 'MPT, BPT',
    institution: 'Maurya College of Physiotherapy',
    city: 'Mysore',
    dateOfBirth: '24 Jan 1989',
    specialization: 'Physiotherapy',
    joiningDate: '03 Nov 2025',
    appointmentType: 'Principal',
    address: '#96, 3rd Cross, Nandini Layout, Alanahalli, Mysuru - 570028',
    previousExperience: 'Assistant Professor and principal-level physiotherapy experience recorded in the declaration form.',
    publications: 'International: 1; National: 1; Other: 5',
    researchProjects: 'Not recorded',
    qualificationDetails: [
      'MPT, KTG College of Physiotherapy/RGUHS, 2016',
      'BPT, JSS College of Physiotherapy/RGUHS, 2013',
    ],
    documentFileName: 'Priyanka.pdf',
    documentStatus: 'PDF available for upload',
    status: 'Active',
    createdAtText: '23 Jun 2026',
  },
  {
    id: 'demo-staff-shreya-kp',
    employeeId: 'FAC-1004',
    name: 'Shreya K P',
    staffType: 'Faculty',
    department: 'Allied Health Sciences',
    designation: 'Tutor',
    phone: '+91 81239 92987',
    email: 'shreyakumar252@gmail.com',
    qualification: 'B.Sc MLT',
    institution: 'Maurya Institute of Allied Health Sciences',
    city: 'Mysore',
    dateOfBirth: '13 Sep 2003',
    specialization: 'Medical Laboratory Technology',
    joiningDate: '11 Mar 2026',
    appointmentType: 'Tutor',
    address: '#103, 2nd Floor, 3rd Main, T.K. Layout, Janathanagar, Mysore - 570001',
    previousExperience: 'Maurya Institute of Allied Health Sciences, 11 Mar 2026 to till date.',
    publications: 'Not recorded',
    researchProjects: 'Not recorded',
    qualificationDetails: [
      'B.Sc, Cauvery College/RGUHS, 2026',
    ],
    documentFileName: 'Shreya k p.pdf',
    documentStatus: 'PDF available for upload',
    status: 'Active',
    createdAtText: '23 Jun 2026',
  },
  {
    id: 'demo-staff-tejas-m',
    employeeId: 'FAC-1005',
    name: 'Tejas M',
    staffType: 'Faculty',
    department: 'Allied Health Sciences',
    designation: 'Assistant Professor',
    phone: '+91 91641 03816',
    email: 'tejasmtejasm53@gmail.com',
    qualification: 'M.Sc Biochemistry, B.Sc BMBt',
    institution: 'Maurya Institute of Allied Health Sciences',
    city: 'Mysore',
    dateOfBirth: '18 Jan 2001',
    specialization: 'Biochemistry',
    joiningDate: '16 Mar 2026',
    appointmentType: 'Assistant Professor',
    address: 'Sri Manjunatha K S, #703, BEML Layout, Rajarajeshwarinagar, Mysore - 570022',
    previousExperience: 'Maurya Institute of Allied Health Sciences, 16 Mar 2026 to till date.',
    publications: 'Not recorded',
    researchProjects: 'Not recorded',
    qualificationDetails: [
      'M.Sc Biochemistry, University of Mysore, 2024',
      'B.Sc BMBt, Yuvaraja College/University of Mysore, 2022',
    ],
    documentFileName: 'Tejas M.pdf',
    documentStatus: 'PDF available for upload',
    status: 'Active',
    createdAtText: '23 Jun 2026',
  },
  {
    id: 'demo-staff-anusha-shine',
    employeeId: 'FAC-1006',
    name: 'Anusha Shine',
    staffType: 'Faculty',
    department: 'Nursing',
    designation: 'Nursing Tutor',
    phone: '+91 94477 48606',
    email: 'anushashine8@gmail.com',
    qualification: 'B.Sc Nursing',
    institution: 'Maurya College of Nursing',
    city: 'Mysore',
    dateOfBirth: '28 Sep 2003',
    specialization: 'Nursing',
    joiningDate: '11 Mar 2026',
    appointmentType: 'Tutor',
    address: 'Aneese Cottage, Pallipattu, Muttom P.O., Kerala - 685587',
    previousExperience: 'Maurya College of Nursing, 11 Mar 2026 to till date.',
    publications: 'Not recorded',
    researchProjects: 'Not recorded',
    qualificationDetails: [
      "B.Sc Nursing, Saint Mary's College of Nursing/RGUHS, 2025",
    ],
    documentFileName: 'ANUSHA SHINE.pdf',
    documentStatus: 'PDF available for upload',
    status: 'Active',
    createdAtText: '23 Jun 2026',
  },
  {
    id: 'demo-staff-chaitra-b',
    employeeId: 'FAC-1007',
    name: 'Chaitra B',
    staffType: 'Faculty',
    department: 'Nursing',
    designation: 'Nursing Tutor',
    phone: '+91 91136 10334',
    email: 'chaitrabadiger087@gmail.com',
    qualification: 'B.Sc Nursing',
    institution: 'Maurya College of Nursing',
    city: 'Mysore',
    dateOfBirth: '23 Jul 2001',
    specialization: 'Nursing',
    joiningDate: '23 Mar 2026',
    appointmentType: 'Tutor',
    address: 'C/o Basavaraj, Chivaragar, Tq. Kustagi, Dist. Koppal',
    previousExperience: 'Maurya College of Nursing, 23 Mar 2026 to till date.',
    publications: 'Not recorded',
    researchProjects: 'Not recorded',
    qualificationDetails: [
      "B.Sc Nursing, Saint Mary's College of Nursing/RGUHS, 2025",
    ],
    documentFileName: 'CHAITRA B.pdf',
    documentStatus: 'PDF available for upload',
    status: 'Active',
    createdAtText: '23 Jun 2026',
  },
  {
    id: 'demo-staff-chandana-hs',
    employeeId: 'FAC-1008',
    name: 'Chandana H S',
    staffType: 'Faculty',
    department: 'Nursing',
    designation: 'Nursing Tutor',
    phone: '+91 90361 14986',
    email: 'mudduchandu785@gmail.com',
    qualification: 'B.Sc Nursing',
    institution: 'Maurya College of Nursing',
    city: 'Mysore',
    dateOfBirth: '28 Oct 2003',
    specialization: 'Nursing',
    joiningDate: '13 Mar 2026',
    appointmentType: 'Tutor',
    address: 'Somanahalli (V), Nanjangud Taluk, Mysore District - 571118',
    previousExperience: 'Maurya College of Nursing, 13 Mar 2026 to till date.',
    publications: 'Not recorded',
    researchProjects: 'Not recorded',
    qualificationDetails: [
      'B.Sc Nursing, Gopala Gowda Shanthaveri Memorial College of Nursing/RGUHS, 2025',
    ],
    documentFileName: 'CHANDANA H S.pdf',
    documentStatus: 'PDF available for upload',
    status: 'Active',
    createdAtText: '23 Jun 2026',
  },
];

export const demoLeaveRecords = [
  {
    id: 'demo-leave-1',
    staffRecordId: 'demo-staff-harish-b',
    employeeId: 'FAC-1002',
    leaveType: 'Casual Leave',
    fromDate: '2026-06-20',
    toDate: '2026-06-21',
    reason: 'Family function',
    status: 'Pending Review',
    requestedAtText: '18 Jun 2026',
  },
];

export const demoAttendanceRecords = [
  {
    id: 'demo-attendance-1',
    staffRecordId: 'demo-staff-deepashree-cl',
    employeeId: 'FAC-1001',
    dateText: '18 Jun 2026',
    status: 'Present',
    markedAtText: '18 Jun 2026',
  },
];
